# Site settings
title: Prince Mensah
email: princemensah@aims.edu.gh
description: > # this means to ignore newlines until "baseurl:"
  Passionate about developing end-to-end AI solutions and solving real-world problems through intelligent automation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://princeemensah.github.io" # the base hostname & protocol for your site
production_url: "https://princeemensah.github.io"
github_username: princeemensah
permalink: /blog/:year/:month/:title.html

# FontAwesome configuration
fontawesome_kit_id: "your-kit-id" # Replace with your actual FontAwesome kit ID

twitter:
  username: princeemensah

# SCSS processing
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
